### ISSUE TITLE
SqlConnector

### ISSUE THREAD

**Issue by KVAK0** [FlexSearch/FlexSearch#50]
Hi,

First of all, thank you for doing a great job with FlexSearch

I do have one question though - I've been trying to rewrite SqlConnector into C# but I got stuck at the
CommonApi.Sql method call (gives me error 400, "The requested URI endpoint is not supported.")

Digging deeper, I couldn't get it to work with either Swagger nor Fiddler (please find attached screenshots)

Could you please take a quick look - maybe I'm missing something important

The API is running well, all the endpoints are working fine except this one /indices/index/sql
Thank you for any help

Best regards,
Martin

![swagger](https://cloud.githubusercontent.com/assets/23332718/20093769/6c4c7334-a59e-11e6-8643-bd0cfdf1d9e4.png)

![fiddler](https://cloud.githubusercontent.com/assets/23332718/20093777/705cd356-a59e-11e6-9490-f2c34bf8ff96.png)

**Comment by vladnega** [comment]
Hi @KVAK0 

Thank you for your interest in FlexSearch. 

My guess is that you didn't put the SQL Connector plugin DLL into the `Plugins` folder. I have now included the `SqlConnector.dll` plugin in the [latest release](https://github.com/FlexSearch/FlexSearch/releases/tag/0.7.6). 

You can find more information about the SQL Connector in this [documentation page](https://flexsearch.net/docs/connectors/sql-connector/). I will update it to make it clear that the plugin needs to be installed in order to get the SQL endpoint working. More information about installing *FlexSearch plugins* can be found at the bottom of [this page](https://flexsearch.net/docs/extending/custom-plugins/).

Let me know if you're still hitting the same issue.

**Comment by KVAK0** [comment]
Hi vladnega,

Thank you for your help - I didn't have DLL's there
Now I've put the SQL Connector plugin DLL into the Plugins folder and came up with this:

> FSLog Warning: 7002 : Error Code: Generic
> Message: Error loading plug-in library.
> An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
> **************************************************
> Type: System.NotSupportedException
> TargetSite: System.Reflection.RuntimeAssembly nLoadFile(System.String, System.Security.Policy.Evidence)
> Source: mscorlib
> HResult: -2146233067
> 
> StackTrace
> **************************************************
> 
>    at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
>    at System.Reflection.Assembly.LoadFile(String path)
>    at Startup.loadAllPlugins()
> 

I've fixed this one by adding
<loadFromRemoteSources enabled="true"/> into FlexSearch-Server.exe.config file
Startup went OK (FSLog Information: 7003 : Message: Loaded external plugin SqlConnector.dll)
but still - I'm receiving same issue when trying to call API sql functions via Swagger
(http://localhost:9800/portal/apps/swagger/#/swagger?open=sql)

I've tried same thing with CSV plugin - no luck
Could it be because of the .NET version is different? 

Thank you for the answer,
Martin

**Comment by vladnega** [comment]
Oh, maybe your `SqlConnector.dll` file is blocked. Could you right-click it and unblock it?

**Comment by KVAK0** [comment]
Hi vladnega,

Thank you for your help
I've unblocked my SqlConnector.dll file, but unfortunately I'm still hitting the same issue 

![startup](https://cloud.githubusercontent.com/assets/23332718/20183307/233e63aa-a765-11e6-82ae-5d34555e4b5e.PNG)

![swagger](https://cloud.githubusercontent.com/assets/23332718/20183296/1e9fd7ac-a765-11e6-83f0-07f1e2fcb71e.png)

I've got no clue what the cause might be

**Comment by vladnega** [comment]
Sorry about this. I will investigate it further this evening.

**Comment by vladnega** [comment]
Martin, I've updated the *SqlConnector.dll* in the latest release of FlexSearch. Could you please download it and try it again?

If you're interested, you can see the changes I've made to the *SqlConnector.dll* [here](https://github.com/FlexSearch/SqlConnector/commit/4327f9bdc20bf9699d2512d1ab76a46c06192905).

**Comment by persiandeveloper** [comment]
I also have same problem. Unlocked  the dll restarted the server and no luck.
