### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by chogue** [FlexSearch/FlexSearch#54]
FlexSearch.Api/client/ApiClient.cs, ApiException.cs, ApiResponse.cs

**Comment by vladnega** [comment]
@chogue, are you running into issues when trying to run the already built package (the zip file in the *Releases* section), or when trying to build the project you have cloned?

If you're trying to just build the project you have cloned, then these files are generated automatically when you run `./build api`. They are generated from the swagger file found in the `spec` folder.

Let me know if this solves your problem.

**Comment by chogue** [comment]
Ah, ok... I didn't actually "kick" the build process, I was just attempting to "build all" via VS.... now that you mention it tho, I am not having much luck with "running" the downloaded app.

It seems to be ok when it is "run", via FlexSearch-Server.exe command, and it appears that it is listening on :9800 however, the portal never responds when requesting http://localhost:9800... and when a "post" is attempted via Postman I receive the following exception:

at Microsoft.Extensions.Primitives.InplaceStringBuilder.Append(String s)
   at Microsoft.Net.Http.Headers.DateTimeFormatter.ToRfc1123String(DateTimeOffse
t dateTime, Boolean quoted)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.DateHeaderValueManager.S
etDateValues(DateTimeOffset value)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.DateHeaderValueManager.S
tartTimer()
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.CreateResponseHead
er(Byte[] statusBytes, Boolean appCompleted)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.InitializeResponse
(Int32 firstWriteByteCount)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame.Write(ArraySegment
`1 data)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.FrameResponseStream.Writ
e(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.StreamWriter.Close()
   at Newtonsoft.Json.JsonTextWriter.Close()
   at Newtonsoft.Json.JsonWriter.Dispose(Boolean disposing)
   at Newtonsoft.Json.JsonWriter.System.IDisposable.Dispose()
   at FlexSearch.Core.NewtonsoftJsonFormatter.FlexSearch-Core-IFormatter-Seriali
ze(Object body, Stream stream)
   at FlexSearch.Core.Http.requestProcessor@267-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@841.Invoke(AsyncParams`1 a
rgs)

**Comment by vladnega** [comment]
Thank you for noticing. I have raised issue #55 for this exception and will close the current issue.
